MOCS=colorselectorwidget_moc.cpp comboboxwidget_moc.cpp fileselectorwidget_moc.cpp fontselectorwidget_moc.cpp lineeditwidget_moc.cpp numberselectorwidget_moc.cpp radiobuttonwidget_moc.cpp spinboxwidget_moc.cpp videowallselectorwidget_moc.cpp 



ALL: $(MOCS)

%_moc.cpp: %.h
	moc -o $@ $<

clean:
	rm *moc*







