.TH gephex 1   
.SH NAME
gephex \- gephex video effect software
.SH DESCRIPTION
gephex is the central binary of
the interactive video effect system GePhex. It starts both
\fBgephex\-engine \fR(1)
and \fBgephex\-gui\fR(1).
.PP
There are no command line parameters.
All parameters are set in the config file.
The GEPHEX_XTERM environment variable is used to choose
an x terminal emulator in which the engine is started.
The GEPHEX_XTERM_FLAGS variable can be used to pass extra flags
to this terminal emulator.
.PP
The projects main intent is to create a framework that allows video\-jockeys
to design complex real\-time video effects. The user can influence parameters
and data flow with interactive controls like joysticks or midi devices.
.SH FILES
\fB~/.gephex/0.4/gephex.conf\fR
.SH "SEE ALSO"
\fBgephex\-engine\fR(1)
.PP
\fBgephex\-gui\fR(1)
.PP
http://www.gephex.org for the original source and main 
arch archive.
.SH AUTHORS
Martin Bayer martin@gephex.org
.PP
Georg Seidel georg@gephex.org
.PP
Philipp Promesberger coma@gephex.org
