.TH gephex\-engine 1   
.SH NAME
gephex\-engine \- back\-end for the video effect software
.SH DESCRIPTION
gephex\-engine is the main component of the interactive video effect system GePhex. You have to start the engine and can then connect with the \fBgephex\-gui\fR(1).
.PP
There are no command line parameters.
All parameters are set in the config file.
.PP
The projects main intent is to create a framework that allows video\-jockeys to design complex real\-time video effects. The user can influence parameters 
and data flow with interactive controls like joysticks or midi devices.
.SH FILES
\fB~/.gephex/gephex.conf\fR
.SH SEE\ ALSO
\fBgephex\fR(1)
.PP
\fBgephex\-gui\fR(1)
.PP
http://www.gephex.org for the original source and main 
arch archive.
.SH AUTHORS
Martin Bayer martin@gephex.org
.PP
Georg Seidel georg@gephex.org
.PP
Philipp Promesberger coma@gephex.org